const passport = require("passport")
const GoogleStrategy = require("passport-google-oauth20")
const mongoose = require("mongoose")
const keys = require("../config/keys")

const User = mongoose.model("users")

//create cookie
passport.serializeUser((user, done) => {
  done(null, user.id) //this user.id is the userId generated by mongo, not the google id
})

//get cookie
passport.deserializeUser((id, done) => {
  User.findById(id).then(user => {
    done(null, user)
  })
})

passport.use(
  new GoogleStrategy(
    {
      clientID: keys.googleClientID,
      clientSecret: keys.googleClientSecret,
      callbackURL: "/auth/google/callback",
      proxy: true
    },
    (accessToken, refreshToken, profile, done) => {
      User.findOne({ googleId: profile.id }).then(existingUser => {
        if (!existingUser) {
          new User({ googleId: profile.id }).save().then(user => done(null, user))
        } else {
          done(null, existingUser)
        }
      })
    }
  )
)
